"""
coding/ProjectGenerator.py
==========================
Generates complete boilerplate project structures, configurations,
dependencies, Dockerfiles, and readme blueprints.
"""

import logging
from typing import Dict, Any, List

logger = logging.getLogger("msa.coding.project_generator")

class ProjectGenerator:
    def __init__(self, llm: Any = None):
        self.llm = llm

    def generate(self, project_type: str, name: str, description: str = "") -> Dict[str, Any]:
        """
        Generates full template directory list and code assets based on project type.
        """
        project_type = project_type.lower()
        if not description:
            description = f"Boilerplate {project_type} project generated by MSA."

        if project_type == "springboot" or "spring" in project_type:
            return self.generate_springboot(name, description)
        elif project_type == "angular":
            return self.generate_angular(name, description)
        elif project_type == "react":
            return self.generate_react(name, description)
        elif project_type == "nodejs" or "node" in project_type:
            return self.generate_nodejs(name, description)
        elif project_type == "microservices" or "docker" in project_type:
            return self.generate_microservices(name, description)
        else:
            # Fallback NodeJS
            return self.generate_nodejs(name, description)

    def generate_springboot(self, name: str, description: str) -> Dict[str, Any]:
        pom_xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.2</version>
        <relativePath/>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>{name}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>{name}</name>
    <description>{description}</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""

        application_yml = """server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
"""

        main_class = f"""package com.example.{name};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {{
    public static void main(String[] args) {{
        SpringApplication.run(Application.class, args);
    }}
}}
"""

        dockerfile = f"""FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
COPY target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
"""

        readme = f"""# {name}

Spring Boot REST project: {description}

## Prerequisites
- JDK 17
- Maven 3.8+

## Quick Start
```bash
mvn clean package
java -jar target/{name}-0.0.1-SNAPSHOT.jar
```
"""

        return {
            "project_type": "springboot",
            "name": name,
            "blueprint": {
                "directories": [
                    "src/main/java/com/example/" + name,
                    "src/main/resources",
                    "src/test/java/com/example/" + name
                ],
                "files": [
                    {"path": "pom.xml", "content": pom_xml},
                    {"path": "src/main/resources/application.yml", "content": application_yml},
                    {"path": f"src/main/java/com/example/{name}/Application.java", "content": main_class},
                    {"path": "Dockerfile", "content": dockerfile},
                    {"path": "README.md", "content": readme}
                ]
            }
        }

    def generate_angular(self, name: str, description: str) -> Dict[str, Any]:
        package_json = f"""{{
  "name": "{name}",
  "version": "0.0.0",
  "scripts": {{
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test"
  }},
  "dependencies": {{
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/router": "^17.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.0"
  }}
}}
"""

        angular_json = f"""{{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {{
    "{name}": {{
      "projectType": "application",
      "root": "",
      "sourceRoot": "src"
    }}
  }}
}}
"""

        app_component = """import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<h1>Welcome to Angular Application!</h1>',
  styles: []
})
export class AppComponent {
  title = 'angular-app';
}
"""

        readme = f"""# {name}

Angular application: {description}

## Quick Start
```bash
npm install
npm start
```
"""

        return {
            "project_type": "angular",
            "name": name,
            "blueprint": {
                "directories": [
                  "src/app",
                  "src/assets",
                  "src/environments"
                ],
                "files": [
                    {"path": "package.json", "content": package_json},
                    {"path": "angular.json", "content": angular_json},
                    {"path": "src/app/app.component.ts", "content": app_component},
                    {"path": "README.md", "content": readme}
                ]
            }
        }

    def generate_react(self, name: str, description: str) -> Dict[str, Any]:
        package_json = f"""{{
  "name": "{name}",
  "version": "1.0.0",
  "dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1"
  }},
  "scripts": {{
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test"
  }}
}}
"""

        app_js = """import React from 'react';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Welcome to React Application</h1>
      </header>
    </div>
  );
}

export default App;
"""

        readme = f"""# {name}

React Application: {description}

## Quick Start
```bash
npm install
npm start
```
"""

        return {
            "project_type": "react",
            "name": name,
            "blueprint": {
                "directories": [
                    "src",
                    "public"
                ],
                "files": [
                    {"path": "package.json", "content": package_json},
                    {"path": "src/App.js", "content": app_js},
                    {"path": "README.md", "content": readme}
                ]
            }
        }

    def generate_nodejs(self, name: str, description: str) -> Dict[str, Any]:
        package_json = f"""{{
  "name": "{name}",
  "version": "1.0.0",
  "description": "{description}",
  "main": "server.js",
  "dependencies": {{
    "express": "^4.18.2"
  }},
  "scripts": {{
    "start": "node server.js"
  }}
}}
"""

        server_js = """const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/api/health', (req, res) => {
    res.json({ status: 'UP', timestamp: new Date() });
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
"""

        dockerfile = """FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]
"""

        readme = f"""# {name}

NodeJS REST Server: {description}

## Quick Start
```bash
npm install
npm start
```
"""

        return {
            "project_type": "nodejs",
            "name": name,
            "blueprint": {
                "directories": [
                    "routes",
                    "middleware",
                    "config"
                ],
                "files": [
                    {"path": "package.json", "content": package_json},
                    {"path": "server.js", "content": server_js},
                    {"path": "Dockerfile", "content": dockerfile},
                    {"path": "README.md", "content": readme}
                ]
            }
        }

    def generate_microservices(self, name: str, description: str) -> Dict[str, Any]:
        compose_yml = f"""version: '3.8'

services:
  gateway:
    image: gateway-service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  customer-service:
    image: customer-service:latest
    ports:
      - "8081:8081"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/customers

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=customers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
"""

        readme = f"""# {name} Microservices

Docker-compose environment stack: {description}

## Orchestration run
```bash
docker-compose up -d
```
"""

        return {
            "project_type": "microservices",
            "name": name,
            "blueprint": {
                "directories": [
                    "gateway-service",
                    "customer-service",
                    "db-init"
                ],
                "files": [
                    {"path": "docker-compose.yml", "content": compose_yml},
                    {"path": "README.md", "content": readme}
                ]
            }
        }
