"""
backend/artifact_engine/artifact_models.py
===========================================
Pydantic models for Artifacts (version-tracked markdown, code, design files).
"""
from __future__ import annotations

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class ArtifactVersion(BaseModel):
    """Specific version of an artifact."""
    version: int = Field(..., description="Incremental version number")
    content: str = Field(..., description="The content at this version")
    description: str = Field(default="", description="Description of changes made in this version")
    created_at: float = Field(..., description="Timestamp when version was created")


class Artifact(BaseModel):
    """System-wide Artifact model representing a document/file generated by AI."""
    id: str = Field(..., description="Unique slugified ID of the artifact")
    title: str = Field(..., description="User-facing title")
    file_type: str = Field(..., description="code|diagram|html|markdown|table")
    language: Optional[str] = Field(default=None, description="Syntax highlighting language (e.g. python, html)")
    workspace_id: str = Field(default="default", description="Namespace workspace ID")
    current_version: int = Field(default=1, description="Latest version number")
    versions: List[ArtifactVersion] = Field(default_factory=list, description="All revisions of the artifact")
    created_at: float = Field(..., description="Initial creation timestamp")
    updated_at: float = Field(..., description="Latest revision timestamp")
